import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


class SuperColliderStaticTests(unittest.TestCase):
    def test_tape_deck_exposes_python_render_load_modes(self) -> None:
        text = (REPO_ROOT / "SC" / "cutup.scd").read_text(encoding="utf-8")
        for marker in (
            "~scanLiveTrack",
            "~scanChunksFolder",
            "~scanCurrentSource",
            "LOAD DIR",
            "LOAD LIVE",
            "LOAD CHUNKS",
            "Single audio file selected",
            "AUDIO FILES FOUND",
            "flac",
            "*_live_track.wav",
            "chunks",
            "REFRESH CHUNKS",
            "LIVE TRACK",
            "\\liveTrackTape",
            "~startChunkRefresh",
            "~refreshChunksOnce",
            "~startLiveTrack",
            "~hardStopLiveTrack",
            "SC INPUT",
            "SC CUTS",
            "SC SRC",
            "BED LOOP",
            "BED REV",
            "SLOTS",
            "ODUB",
            "DECAY",
            "SC PRE",
            "~scPerformancePresetNames",
            "~applyScPerformancePreset",
            "~refreshPerformanceControls",
            "signal-breach",
            "ghost-transmission",
            "beat-stutter",
            "spoken-word",
            "~liveOverdubBus",
            "~liveOverdubSend",
            "overdubSend",
            "\\liveInputRecorderTape",
            "\\liveInputCutTape",
            "\\bedLoopTape",
            "\\liveBedLoopTape",
            "~startLiveInput",
            "~startLiveCutups",
            "~startBedLoops",
            "~fireBedLoop",
            "~hardStopBedLoops",
            "~startBedSlot",
            "~toggleBedSlot",
            "~clearBedSlots",
            "~fireMaterialCut",
            "~fireScCut",
            "~fireLiveInputCut",
            "~liveInputShot",
            "\\concreteCutTape",
            "~concreteShot",
            "CNCR",
            "\\tapeDeckMaster",
            "\\cutupsTapedeckConcrete",
            "/cutups/concrete",
            "/cutups/loadLive",
            "/cutups/loadChunks",
            "/cutups/chunks/refresh",
            "/cutups/live/start",
            "/cutups/live/stop",
            "/cutups/live/amp",
            "/cutups/scLive/input/start",
            "/cutups/scLive/input/stop",
            "/cutups/scLive/cuts/start",
            "/cutups/scLive/cuts/stop",
            "/cutups/scLive/stab",
            "/cutups/scLive/glitch",
            "/cutups/scLive/overdub",
            "/cutups/scLive/decay",
            "/cutups/scLive/source",
            "/cutups/scLive/preset",
            "/cutups/scLive/bed/start",
            "/cutups/scLive/bed/stop",
            "/cutups/scLive/bed/reverse",
            "/cutups/scLive/bed/slot",
            "/cutups/scLive/bed/slot/clear",
            "/cutups/master/age",
            "AGE",
        ):
            self.assertIn(marker, text)


if __name__ == "__main__":
    unittest.main()
